[package]
name = "time_warp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "timewarp"
path = "src/bin/main.rs"

[dependencies]
